# Generated by Django 2.0 on 2021-03-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210319_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='model_pic',
            new_name='image',
        ),
    ]
