# Generated by Django 2.0 on 2021-03-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210319_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null='True', upload_to='foto')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
