# Generated by Django 2.0 on 2021-03-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210319_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(default='none/no-img.jpg', upload_to='foto'),
        ),
    ]
